In [1]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv("saber_11_pro.csv")

C:\Users\JASTYN\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\interactiveshell.py:3441: DtypeWarning: Columns (46,92,99) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [4]:
df.describe()

,PERIODO_x,ESTU_COD_RESIDE_DEPTO_x,ESTU_COD_RESIDE_MCPIO_x,COLE_CODIGO_ICFES,COLE_COD_DANE_ESTABLECIMIENTO,COLE_COD_MCPIO_UBICACION,COLE_COD_DEPTO_UBICACION,PUNT_LENGUAJE,PUNT_MATEMATICAS,PUNT_BIOLOGIA,...,PUNT_MATEMATICAS_norm,PUNT_BIOLOGIA_norm,PUNT_QUIMICA_norm,PUNT_FISICA_norm,PUNT_CIENCIAS_SOCIALES_norm,PUNT_FILOSOFIA_norm,PUNT_INGLES_norm,PUNTAJE_PROF_norm,delta_mat,delta_leng
count,208981.000000,204247.000000,204247.000000,198342.000000,2.089160e+05,208981.000000,208981.000000,208981.000000,208981.000000,208981.000000,...,2.058460e+05,2.058510e+05,2.057440e+05,2.058280e+05,2.059110e+05,2.058670e+05,2.058090e+05,2.052240e+05,205557.000000,205458.000000
mean,20125.890488,31.115801,31280.151694,57247.022194,2.283810e+11,31405.874931,31.232930,51.481498,51.813131,49.469516,...,3.141154e-18,3.434475e-18,-5.456575e-18,-6.904238e-19,-2.984879e-18,1.794762e-18,4.936986e-18,-1.220453e-18,0.002995,0.003236
std,5.165760,26.270253,26299.107698,47102.197875,1.016395e+11,26248.921438,26.221456,7.560608,12.491945,8.201576,...,9.641916e-01,9.641900e-01,9.642996e-01,9.642136e-01,9.641276e-01,9.641677e-01,9.642304e-01,9.647076e-01,1.082622,1.115963
min,20121.000000,5.000000,5001.000000,0.000000,3.110010e+10,5001.000000,5.000000,0.000000,0.000000,-1.000000,...,-4.659068e+00,-4.506272e+00,-5.547069e+00,-5.209439e+00,-4.851976e+00,-5.720487e+00,-5.779585e+00,-8.514696e+00,-12.252039,-11.025942
25%,20122.000000,11.000000,11001.000000,16691.000000,1.234660e+11,11001.000000,11.000000,46.000000,43.000000,44.000000,...,-6.883952e-01,-6.939316e-01,-6.945994e-01,-6.768718e-01,-6.968698e-01,-6.696615e-01,-6.806556e-01,-8.023007e-01,-0.692108,-0.711248
50%,20122.000000,17.000000,17174.000000,42127.000000,1.950010e+11,18001.000000,18.000000,52.000000,51.000000,49.000000,...,-3.084316e-02,-1.628431e-02,-4.703604e-02,0.000000e+00,-2.440323e-02,1.748169e-02,-1.245196e-01,-3.941689e-02,0.032973,0.029552
75%,20132.000000,54.000000,54001.000000,97311.000000,3.117690e+11,54001.000000,54.000000,56.000000,58.000000,54.000000,...,6.538018e-01,6.731289e-01,6.562581e-01,6.698328e-01,6.754544e-01,6.840839e-01,6.018265e-01,8.055294e-01,0.728630,0.749077
max,20141.000000,99.000000,99773.000000,179358.000000,8.548740e+11,99773.000000,99.000000,109.000000,127.000000,100.000000,...,5.614693e+00,5.439033e+00,4.686991e+00,5.104753e+00,5.253478e+00,5.682331e+00,6.626758e+00,9.908555e+00,5.708334,5.992100

In [5]:
df.head(6)

,ESTU_TIPODOCUMENTO_x,ESTU_NACIONALIDAD_x,ESTU_GENERO_x,ESTU_FECHANACIMIENTO_x,PERIODO_x,ESTU_CONSECUTIVO_x,ESTU_ESTUDIANTE_x,ESTU_PAIS_RESIDE_x,ESTU_DEPTO_RESIDE_x,ESTU_COD_RESIDE_DEPTO_x,...,PUNT_MATEMATICAS_norm,PUNT_BIOLOGIA_norm,PUNT_QUIMICA_norm,PUNT_FISICA_norm,PUNT_CIENCIAS_SOCIALES_norm,PUNT_FILOSOFIA_norm,PUNT_INGLES_norm,PUNTAJE_PROF_norm,delta_mat,delta_leng
0,CC,COLOMBIA,M,05/01/1990,20121,SB11201210058388,ESTUDIANTE,COLOMBIA,BOGOTA,11.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,CC,COLOMBIA,M,01/08/1993,20121,SB11201210060023,ESTUDIANTE,COLOMBIA,BOGOTA,11.0,...,0.641619,0.702782,0.833567,0.035991,0.517321,1.208081,1.210200,-1.500000,0.286518,0.625845
2,TI,COLOMBIA,M,27/05/1995,20121,SB11201210060020,ESTUDIANTE,COLOMBIA,BOGOTA,11.0,...,0.180969,0.390434,-0.181210,0.467880,-1.322043,0.201347,-0.745679,0.500000,-0.253827,-0.955353
3,TI,COLOMBIA,M,19/10/1994,20121,SB11201210060017,ESTUDIANTE,COLOMBIA,BOGOTA,11.0,...,-1.464207,-1.483651,-1.340955,-1.403641,-0.172440,-1.208081,-0.892370,0.500000,0.356405,0.499206
4,TI,COLOMBIA,M,16/07/1993,20121,SB11201210060019,ESTUDIANTE,COLOMBIA,BOGOTA,11.0,...,0.641619,0.390434,0.688599,0.899770,0.977162,-0.201347,0.427849,0.500000,-0.122268,0.290902
5,CC,COLOMBIA,F,10/02/1970,20121,SB11201210039541,ESTUDIANTE,COLOMBIA,VALLE,76.0,...,-0.707107,0.707107,0.707107,-0.707107,-0.707107,-0.707107,0.707107,-0.707107,-0.260277,-0.459215

In [6]:
df1=df.head(8)

In [7]:
df1.to_excel("jasty.xlsx")

In [8]:
df3=pd.read_csv("saber_11_pro.csv")

C:\Users\JASTYN\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\interactiveshell.py:3441: DtypeWarning: Columns (46,92,99) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [ ]:
df3.to_excel("change.xlsx")

In [ ]:
df4=pd.read_csv("https://drive.google.com/drive/folders/1uL82iIS7ueScY2uHTLQJvmUrVnj7-NxL")